version: "3.5"

services:
  primary:
    hostname: 'primary'
    image: postgres:11-alpine
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=10
    - MAX_WAL_SENDERS=5
    - PG_MODE=primary
    - PG_PRIMARY_USER=erato_19!@%
    - PG_PRIMARY_PASSWORD=R*vkVy%KJOiq^DdZzBQQj4RpoqWflP
    - PG_DATABASE=testdb
    - PG_USER=klios
    - PG_PASSWORD=positivo95612612
    - PG_ROOT_PASSWORD=TT#OIsv0UkzoayAYP2#96kK@AB^bxn
    - PG_PRIMARY_PORT=5432
    volumes:
    - pg-primary-vol:/pgdata
    ports:
    - "32768:5432"
    networks:
    - crunchynet
    deploy:
      placement:
        constraints:
        - node.labels.type == primary
        - node.role == worker
  replica:
    image: postgres:11-alpine
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=10
    - MAX_WAL_SENDERS=5
    - PG_MODE=replica
    - PG_PRIMARY_HOST=primary
    - PG_PRIMARY_PORT=5432
    - PG_PRIMARY_USER=erato_19!@%
    - PG_PRIMARY_PASSWORD=R*vkVy%KJOiq^DdZzBQQj4RpoqWflP
    - PG_DATABASE=klios
    - PG_USER=renato
    - PG_PASSWORD=positivo95612612
    - PG_ROOT_PASSWORD=TT#OIsv0UkzoayAYP2#96kK@AB^bxn
    volumes:
    - pg-replica-vol:/pgdata
    ports:
    - "32769:5432"
    networks:
    - crunchynet
    deploy:
      placement:
        constraints:
        - node.labels.type != primary
        - node.role == worker
networks:
  crunchynet:

volumes:
  pg-primary-vol:
  pg-replica-vol:
